SAMPLE_REVIEWS = [
    {
        "review": "画面和音乐都很棒，探索地图的时候很有沉浸感。Boss 设计有挑战，但打过之后成就感很强。",
        "voted_up": True,
        "votes_up": 18,
        "votes_funny": 0,
        "weighted_vote_score": "0.85",
        "timestamp_created": 1717046400,
        "author": {"playtime_forever": 4200, "steamid": "demo_1"},
    },
    {
        "review": "优化太差了，更新之后明显掉帧，城市场景经常卡顿，希望尽快修复。",
        "voted_up": False,
        "votes_up": 42,
        "votes_funny": 1,
        "weighted_vote_score": "0.92",
        "timestamp_created": 1717132800,
        "author": {"playtime_forever": 860, "steamid": "demo_2"},
    },
    {
        "review": "剧情不错，支线任务也有意思，但是新手引导不够清楚，刚开始不知道应该去哪里。",
        "voted_up": True,
        "votes_up": 9,
        "votes_funny": 0,
        "weighted_vote_score": "0.71",
        "timestamp_created": 1717219200,
        "author": {"playtime_forever": 2200, "steamid": "demo_3"},
    },
    {
        "review": "服务器不稳定，联机匹配经常断开，和朋友一起玩体验很差。",
        "voted_up": False,
        "votes_up": 27,
        "votes_funny": 0,
        "weighted_vote_score": "0.88",
        "timestamp_created": 1717305600,
        "author": {"playtime_forever": 1330, "steamid": "demo_4"},
    },
    {
        "review": "内容量很足，地图探索和装备搭配都值得研究，打折入手非常划算。",
        "voted_up": True,
        "votes_up": 21,
        "votes_funny": 0,
        "weighted_vote_score": "0.83",
        "timestamp_created": 1717392000,
        "author": {"playtime_forever": 5100, "steamid": "demo_5"},
    },
    {
        "review": "DLC 价格偏贵，新内容没有想象中多，重复刷材料比较无聊。",
        "voted_up": False,
        "votes_up": 35,
        "votes_funny": 2,
        "weighted_vote_score": "0.9",
        "timestamp_created": 1717478400,
        "author": {"playtime_forever": 3100, "steamid": "demo_6"},
    },
    {
        "review": "战斗手感很好，角色成长路线丰富，适合喜欢慢慢研究玩法的人。",
        "voted_up": True,
        "votes_up": 13,
        "votes_funny": 0,
        "weighted_vote_score": "0.79",
        "timestamp_created": 1717564800,
        "author": {"playtime_forever": 2750, "steamid": "demo_7"},
    },
    {
        "review": "遇到两次闪退和一个任务 bug，虽然游戏本身好玩，但现在版本还需要打磨。",
        "voted_up": False,
        "votes_up": 31,
        "votes_funny": 0,
        "weighted_vote_score": "0.89",
        "timestamp_created": 1717651200,
        "author": {"playtime_forever": 1900, "steamid": "demo_8"},
    },
]
